[tool.poetry]
name = "threa"
version = "1.7.0"
description = "🧵 Better threads 🧵"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
coverage = "^7.3.2"

[tool.poetry.group.dev.dependencies]
black = "*"
flake8 = "*"
pytest = "*"
ruff = "*"
mypy = "*"

[tool.mypy]
strict = true

[tool.black]
skip-string-normalization = true
target-version = ["py311"]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
